import type { ReactNode } from 'react';
import { ArrowRight, Check, Database, FileCode2, HeartPulse, Pill, ScanLine, ShieldCheck, Stethoscope, TrendingUp, UserRound } from 'lucide-react';
import { Link } from 'react-router-dom';

const ButtonLink = ({ to, children, secondary = false }: { to: string; children: ReactNode; secondary?: boolean }) => (
  <Link to={to} className={`group inline-flex min-h-11 items-center justify-center gap-2 rounded-full px-5 py-3 text-sm font-semibold transition-all hover:-translate-y-0.5 ${secondary ? 'border border-hairline bg-card/70 text-ink hover:bg-paper-2' : 'bg-ink text-paper shadow-elevated hover:bg-moss-600'}`}>
    {children}<ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" />
  </Link>
);

const Eyebrow = ({ children }: { children: ReactNode }) => <span className="eyebrow-pill"><span className="eyebrow-dot" />{children}</span>;

const MockTimeline = () => (
  <div className="mock-timeline relative overflow-hidden rounded-28 border border-white/25 bg-[#f8f3e8]/90 p-4 text-ink shadow-glass sm:p-6">
    <div className="mb-5 flex items-center justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-ink-soft">Ramesh Kumar</p><h3 className="font-serif text-2xl">Your timeline</h3></div><div className="rounded-full bg-moss-100 px-3 py-1 text-[10px] font-semibold text-moss-600">4 records</div></div>
    <div className="relative space-y-3 before:absolute before:bottom-3 before:left-[13px] before:top-3 before:w-px before:bg-moss-500/40">
      {[['Lab result', 'HbA1c · 6.8%', 'bg-event-lab-bg text-event-lab-text'], ['Prescription', 'Metformin · 500mg', 'bg-event-med-bg text-event-med-text'], ['Consultation', 'Apollo Hospitals', 'bg-event-enc-bg text-event-enc-text']].map(([kind, label, color]) => <div key={kind} className="relative flex items-center gap-3"><span className="z-10 h-7 w-7 rounded-full border-4 border-[#f8f3e8] bg-moss-600" /><div className="flex flex-1 items-center justify-between rounded-2xl border border-hairline bg-card px-3 py-2.5"><div><p className="text-[10px] text-ink-soft">{kind}</p><p className="text-sm font-medium">{label}</p></div><span className={`rounded-full px-2 py-1 text-[9px] font-semibold ${color}`}>NEW</span></div></div>)}
    </div>
    <div className="mt-5 h-12 rounded-xl bg-moss-100/50 p-2"><svg viewBox="0 0 240 32" className="h-full w-full" aria-label="HbA1c trend chart"><path d="M0 26 C35 24,45 9,75 16 S110 27,135 12 S180 5,240 9" fill="none" stroke="#4F6B3A" strokeWidth="2.5" /><path d="M0 26 C35 24,45 9,75 16 S110 27,135 12 S180 5,240 9 L240 32 L0 32Z" fill="#6F8F4E" opacity=".15" /></svg></div>
    <div className="absolute right-5 top-16 z-20 max-w-[185px] animate-float rounded-2xl border border-white/60 bg-white/80 p-3 shadow-glass backdrop-blur-md"><p className="font-mono text-xs font-semibold tracking-wide">APL-RR-1410-RAME</p><p className="mt-1 text-[10px] text-ink-soft">Read this aloud to your doctor</p></div>
  </div>
);

const features = [
  [Pill, 'Speakable Rx-ID', 'No QR codes or login. Read a 16-character code and the doctor sees that prescription, encounter and demographics.', true],
  [HeartPulse, 'Longitudinal health timeline', 'Records from hospitals, labs and pharmacies become one chronological feed with marker trends.', true],
  [FileCode2, 'Resource inspector', 'See raw FHIR resources, declared profiles and the code systems behind every entry.', true],
  [Database, 'Offline-ready', 'A built-in bundle keeps critical history available when the live server is unreachable.', true],
  [TrendingUp, 'Smart savings', 'Match prescribed drugs to lower-cost generic alternatives and flag repeat diagnostics.', false],
  [ScanLine, 'Paper to digital + care gaps', 'Turn paper reports into structured records and surface overdue tests or worsening trends.', false],
] as const;

export const LandingPage = () => <div className="landing-page pb-16">
  <section className="grid items-center gap-10 pt-8 md:grid-cols-[.95fr_1.05fr] md:pt-16">
    <div className="animate-fade-up" style={{ animationDelay: '70ms' }}><Eyebrow>FHIR-NATIVE · PATIENT-OWNED</Eyebrow><h1 className="mt-5 font-serif text-[42px] leading-[1.05] text-ink sm:text-[56px]">Your entire health history, <em>unified and speakable.</em></h1><p className="mt-5 max-w-xl text-base leading-relaxed text-ink-soft">A patient-owned dashboard that turns scattered hospital, lab and pharmacy records into one chronological timeline, built on ABDM/NRCeS standards. Share a prescription with nothing more than a 16-character code you can say out loud.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><ButtonLink to="/patient">Try Patient Dashboard</ButtonLink><ButtonLink to="/clinician" secondary>Try Clinician Lookup</ButtonLink></div><div className="mt-6 flex flex-wrap gap-x-4 gap-y-2 text-xs font-medium text-ink-soft">{['FHIR R4', 'ABDM / NRCeS aligned', 'Works offline'].map(item => <span key={item} className="flex items-center gap-1.5"><Check className="h-3.5 w-3.5 text-moss-600" />{item}</span>)}</div></div>
    <div className="hero-atmosphere animate-fade-up p-4 sm:p-7" style={{ animationDelay: '140ms' }}><MockTimeline /></div>
  </section>

  <div className="my-14 border-y border-hairline py-5 text-center text-xs font-semibold tracking-[.12em] text-ink-soft sm:flex sm:justify-around">{['FHIR R4', 'ABDM', 'NRCeS', 'ABHA', 'SNOMED CT', 'LOINC'].map(x => <span key={x}>{x}</span>)}</div>

  <section id="how-it-works" className="section-reveal py-10 text-center"><h2 className="mx-auto max-w-4xl font-serif text-4xl leading-tight sm:text-5xl">Records are scattered. Care shouldn’t be. <em>Your history should travel with you.</em></h2><p className="mx-auto mt-5 max-w-2xl text-ink-soft">Paper files, repeated tests and disconnected clinics make continuity of care harder than it should be. This demo brings the record back to the person it belongs to.</p></section>
  <section className="section-reveal py-12"><div className="mb-7"><Eyebrow>How it works</Eyebrow></div><div className="grid gap-5 md:grid-cols-3">{[['01', 'Ingest', 'Bring in records from ABHA-linked sources — a live FHIR server or offline bundle today; paper scans coming next.'], ['02', 'Understand', 'See everything on one colour-coded chronological timeline with trends.'], ['03', 'Share', 'Read your Rx-ID aloud; a clinician types it and sees that prescription instantly.']].map(([number, title, text]) => <article key={number} className="rounded-28 border border-hairline bg-card p-6 shadow-soft"><p className="font-serif text-5xl text-moss-600/70">{number}</p><h3 className="mt-4 font-serif text-2xl">{title}</h3><p className="mt-2 text-sm leading-relaxed text-ink-soft">{text}</p></article>)}</div></section>
  <section id="features" className="section-reveal py-12"><div className="mb-7"><Eyebrow>Built for continuity</Eyebrow><h2 className="mt-3 font-serif text-4xl">Every record, in its <em>right context.</em></h2></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{features.map(([Icon, title, copy, live]) => <article key={title} className="rounded-20 border border-hairline bg-card p-5 shadow-soft transition-transform hover:-translate-y-1"><div className="flex items-start justify-between"><span className="rounded-xl bg-moss-100 p-2.5 text-moss-600"><Icon className="h-5 w-5" /></span><span className={`rounded-full border px-2.5 py-1 text-[10px] font-semibold ${live ? 'border-moss-500/30 bg-moss-100 text-moss-600' : 'border-gold-400/60 text-gold-400'}`}>{live ? 'Live in demo' : 'Coming next'}</span></div><h3 className="mt-5 font-serif text-2xl">{title}</h3><p className="mt-2 text-sm leading-relaxed text-ink-soft">{copy}</p></article>)}</div></section>
  <section className="section-reveal my-10 overflow-hidden rounded-28 bg-[#172119] p-6 text-[#f1ede0] sm:p-10"><Eyebrow>One connected view</Eyebrow><h2 className="mt-4 font-serif text-4xl text-gold-400 sm:text-5xl">Turn records into <em>real answers.</em></h2><div className="mt-8 grid gap-4 md:grid-cols-3">{[['Timeline', 'A chronological clinical story'], ['Trend chart', 'HbA1c tracked over time'], ['Digital prescription', 'Speakable Rx-ID at point of care']].map(([title, copy]) => <div key={title} className="rounded-20 border border-white/15 bg-white/5 p-5"><p className="font-serif text-2xl text-gold-400">{title}</p><div className="my-5 h-1.5 rounded-full bg-moss-500/50" /><p className="text-sm text-[#aab5a6]">{copy}</p></div>)}</div><div className="mt-6 grid gap-3 sm:grid-cols-3">{['4 FHIR resource types parsed', '16-character speakable ID', '0 network calls in offline mode'].map(x => <div key={x} className="rounded-xl border border-white/15 p-3 text-center text-xs text-[#d6ddcf]">{x}</div>)}</div></section>
  <section id="patients" className="section-reveal grid gap-4 py-12 md:grid-cols-2"><article className="rounded-28 border border-hairline bg-card p-7"><UserRound className="h-6 w-6 text-moss-600" /><h2 className="mt-5 font-serif text-3xl">For patients</h2><ul className="mt-4 space-y-2 text-sm text-ink-soft"><li>• See your records in one timeline</li><li>• Follow meaningful trends</li><li>• Share a prescription with a spoken ID</li></ul><div className="mt-6"><ButtonLink to="/patient">Open dashboard</ButtonLink></div></article><article id="doctors" className="rounded-28 border border-hairline bg-paper-2 p-7"><Stethoscope className="h-6 w-6 text-teal-700" /><h2 className="mt-5 font-serif text-3xl">For doctors</h2><ul className="mt-4 space-y-2 text-sm text-ink-soft"><li>• Look up an Rx-ID in seconds</li><li>• See context around the prescription</li><li>• Inspect the source FHIR record</li></ul><div className="mt-6"><ButtonLink to="/clinician" secondary>Try clinician lookup</ButtonLink></div></article></section>
  <aside className="rounded-20 border border-moss-500/25 bg-moss-100/45 px-5 py-4 text-center text-sm text-ink-soft"><ShieldCheck className="mr-2 inline h-4 w-4 text-moss-600" />Built on FHIR R4 and ABDM/NRCeS standards · Offline-ready · Your data stays in your browser in this demo.</aside>
  <section className="section-reveal py-20 text-center"><h2 className="font-serif text-5xl">See your history, <em>in one place.</em></h2><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><ButtonLink to="/patient">Try Patient Dashboard</ButtonLink><ButtonLink to="/clinician" secondary>Try Clinician Lookup</ButtonLink></div></section>
</div>;
